name: islamic_text_example
publish_to: "none"
description: Example app for the islamic_text package.

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  islamic_text:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
